"""initial schema

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_counters',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('window_start', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.Integer(), nullable=True),
    sa.CheckConstraint("status in ('preview','active','disabled')", name='ck_tenant_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('phone_norm', sa.String(length=20), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_client_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'phone_norm', name='uq_client_phone')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('gallery_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=200), nullable=False),
    sa.Column('caption', sa.String(length=160), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('config_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gallery_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gallery_photos_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('idempotency_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'scope', 'key', name='uq_idempotency')
    )
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_keys_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('memberships',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tenant_id')
    )
    op.create_table('owner_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('owner_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_owner_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('owner_edited', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_resource_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_resource_tenant_key')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('schedule_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('open_min', sa.Integer(), nullable=True),
    sa.Column('close_min', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=120), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'date', name='uq_exception_date')
    )
    with op.batch_alter_table('schedule_exceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_exceptions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_minor', sa.Integer(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('buffer_min', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('owner_edited', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('price_minor >= 0 AND duration_min > 0 AND buffer_min >= 0', name='ck_service_values'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_service_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_service_tenant_key')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tenant_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('tagline', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('map_url', sa.String(length=300), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('accent', sa.String(length=9), nullable=False),
    sa.Column('logo_path', sa.String(length=200), nullable=True),
    sa.Column('hero_path', sa.String(length=200), nullable=True),
    sa.Column('info_cards', sa.JSON(), nullable=False),
    sa.Column('cancel_before_hours', sa.Integer(), nullable=False),
    sa.Column('slot_step_min', sa.Integer(), nullable=False),
    sa.Column('lead_time_min', sa.Integer(), nullable=False),
    sa.Column('max_advance_days', sa.Integer(), nullable=False),
    sa.Column('reminder_hours', sa.Integer(), nullable=False),
    sa.Column('owner_edited', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('slot_step_min % 15 = 0 AND slot_step_min > 0', name='ck_step_grid'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_settings_tenant')
    )
    with op.batch_alter_table('tenant_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_settings_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('working_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('open_min', sa.Integer(), nullable=False),
    sa.Column('close_min', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6 AND open_min >= 0 AND close_min <= 1440 AND close_min > open_min', name='ck_hours'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'weekday', name='uq_hours_weekday')
    )
    with op.batch_alter_table('working_hours', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_working_hours_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('start_min', sa.Integer(), nullable=False),
    sa.Column('end_min', sa.Integer(), nullable=False),
    sa.Column('buffer_min', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=False),
    sa.Column('price_minor', sa.Integer(), nullable=False),
    sa.Column('car', sa.String(length=80), nullable=False),
    sa.Column('plate', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('access_hash', sa.String(length=64), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('cancelled_at', sa.Integer(), nullable=True),
    sa.Column('cancelled_by', sa.String(length=8), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("status in ('booked','accepted','ready','cancelled')", name='ck_booking_status'),
    sa.CheckConstraint('end_min > start_min AND price_minor >= 0', name='ck_booking_range'),
    sa.ForeignKeyConstraint(['tenant_id', 'client_id'], ['clients.tenant_id', 'clients.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'resource_id'], ['resources.tenant_id', 'resources.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'service_id'], ['services.tenant_id', 'services.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_hash', name='uq_booking_access_hash'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_booking_tenant_id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index('ix_booking_tenant_start', ['tenant_id', 'start_min'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('service_resources',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'resource_id'], ['resources.tenant_id', 'resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'service_id'], ['services.tenant_id', 'services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_id', 'resource_id')
    )
    with op.batch_alter_table('service_resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_resources_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('notification_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('audience', sa.String(length=8), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=False),
    sa.Column('run_at', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('lease_until', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=300), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'booking_id'], ['bookings.tenant_id', 'bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'dedupe_key', name='uq_job_dedupe')
    )
    with op.batch_alter_table('notification_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_job_due', ['status', 'run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_jobs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("amount_minor > 0 AND kind in ('payment','refund')", name='ck_payment'),
    sa.ForeignKeyConstraint(['tenant_id', 'booking_id'], ['bookings.tenant_id', 'bookings.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('ix_payment_tenant_time', ['tenant_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audience', sa.String(length=8), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(length=600), nullable=False),
    sa.Column('p256dh', sa.String(length=200), nullable=False),
    sa.Column('auth', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('disabled_at', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("audience in ('client','owner')", name='ck_push_audience'),
    sa.ForeignKeyConstraint(['tenant_id', 'booking_id'], ['bookings.tenant_id', 'bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'audience', 'endpoint', 'booking_id', name='uq_push_endpoint')
    )
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscriptions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('resource_occupancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('start_min', sa.Integer(), nullable=False),
    sa.Column('end_min', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("(kind = 'booking') = (booking_id IS NOT NULL)", name='ck_occ_booking_link'),
    sa.CheckConstraint("kind in ('booking','block')", name='ck_occ_kind'),
    sa.CheckConstraint('end_min > start_min', name='ck_occ_range'),
    sa.ForeignKeyConstraint(['tenant_id', 'booking_id'], ['bookings.tenant_id', 'bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'resource_id'], ['resources.tenant_id', 'resources.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_occ_tenant_id')
    )
    with op.batch_alter_table('resource_occupancies', schema=None) as batch_op:
        batch_op.create_index('ix_occ_resource_range', ['resource_id', 'start_min', 'end_min'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_occupancies_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('occupancy_cells',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('cell', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('occupancy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'occupancy_id'], ['resource_occupancies.tenant_id', 'resource_occupancies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'resource_id'], ['resources.tenant_id', 'resources.id'], ),
    sa.PrimaryKeyConstraint('resource_id', 'cell', name='uq_occupancy_cell'),
    sqlite_with_rowid=False
    )
    with op.batch_alter_table('occupancy_cells', schema=None) as batch_op:
        batch_op.create_index('ix_cell_occupancy', ['occupancy_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupancy_cells', schema=None) as batch_op:
        batch_op.drop_index('ix_cell_occupancy')

    op.drop_table('occupancy_cells')
    with op.batch_alter_table('resource_occupancies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_occupancies_tenant_id'))
        batch_op.drop_index('ix_occ_resource_range')

    op.drop_table('resource_occupancies')
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_tenant_id'))

    op.drop_table('push_subscriptions')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_tenant_id'))
        batch_op.drop_index('ix_payment_tenant_time')

    op.drop_table('payments')
    with op.batch_alter_table('notification_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_jobs_tenant_id'))
        batch_op.drop_index('ix_job_due')

    op.drop_table('notification_jobs')
    with op.batch_alter_table('service_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_resources_tenant_id'))

    op.drop_table('service_resources')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_tenant_id'))
        batch_op.drop_index('ix_booking_tenant_start')

    op.drop_table('bookings')
    with op.batch_alter_table('working_hours', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_working_hours_tenant_id'))

    op.drop_table('working_hours')
    with op.batch_alter_table('tenant_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_settings_tenant_id'))

    op.drop_table('tenant_settings')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_tenant_id'))

    op.drop_table('services')
    with op.batch_alter_table('schedule_exceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_exceptions_tenant_id'))

    op.drop_table('schedule_exceptions')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_tenant_id'))

    op.drop_table('resources')
    with op.batch_alter_table('owner_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_owner_sessions_user_id'))

    op.drop_table('owner_sessions')
    op.drop_table('memberships')
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_tenant_id'))

    op.drop_table('idempotency_keys')
    with op.batch_alter_table('gallery_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gallery_photos_tenant_id'))

    op.drop_table('gallery_photos')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_tenant_id'))

    op.drop_table('clients')
    op.drop_table('users')
    op.drop_table('tenants')
    op.drop_table('rate_counters')
    # ### end Alembic commands ###
