"""profiles: resource schedules and offers

Revision ID: 0002
Revises: 0001
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('open_min', sa.Integer(), nullable=True),
    sa.Column('close_min', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=120), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'resource_id'], ['resources.tenant_id', 'resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'date', name='uq_resource_exception_date')
    )
    with op.batch_alter_table('resource_exceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_exceptions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('resource_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('open_min', sa.Integer(), nullable=False),
    sa.Column('close_min', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6 AND open_min >= 0 AND close_min <= 1440 AND close_min > open_min', name='ck_resource_hours'),
    sa.ForeignKeyConstraint(['tenant_id', 'resource_id'], ['resources.tenant_id', 'resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'weekday', name='uq_resource_hours_weekday')
    )
    with op.batch_alter_table('resource_hours', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_hours_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=300), server_default='', nullable=False))
        batch_op.add_column(sa.Column('photo_path', sa.String(length=200), nullable=True))

    with op.batch_alter_table('service_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_minor', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('duration_min', sa.Integer(), nullable=True))

    with op.batch_alter_table('tenant_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_type', sa.String(length=24), server_default='auto', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_settings', schema=None) as batch_op:
        batch_op.drop_column('business_type')

    with op.batch_alter_table('service_resources', schema=None) as batch_op:
        batch_op.drop_column('duration_min')
        batch_op.drop_column('price_minor')

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_column('photo_path')
        batch_op.drop_column('description')

    with op.batch_alter_table('resource_hours', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_hours_tenant_id'))

    op.drop_table('resource_hours')
    with op.batch_alter_table('resource_exceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_exceptions_tenant_id'))

    op.drop_table('resource_exceptions')
    # ### end Alembic commands ###
