"""plans, domains, operators, audit

Revision ID: 0003
Revises: 0002
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=254), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)

    op.create_table('operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('admin_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('admin_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_sessions_operator_id'), ['operator_id'], unique=False)

    op.create_table('tenant_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=253), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('verified_at', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("status in ('pending','active','disabled')", name='ck_domain_status'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host')
    )
    with op.batch_alter_table('tenant_domains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_domains_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.String(length=16), server_default='start', nullable=False))
        batch_op.add_column(sa.Column('trial_ends_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('paid_until', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('suspended', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('notes', sa.Text(), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('suspended')
        batch_op.drop_column('paid_until')
        batch_op.drop_column('trial_ends_at')
        batch_op.drop_column('plan')

    with op.batch_alter_table('tenant_domains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_domains_tenant_id'))

    op.drop_table('tenant_domains')
    with op.batch_alter_table('admin_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_sessions_operator_id'))

    op.drop_table('admin_sessions')
    op.drop_table('operators')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
