const MESSAGES: Record<string, string> = {
  network_error: "Нет соединения. Проверьте интернет и повторите.",
  server_error: "Что-то пошло не так на сервере. Попробуйте ещё раз.",
  too_many_requests: "Слишком много запросов. Подождите минуту.",
  validation_error: "Проверьте введённые данные.",
  slot_unavailable: "Это время только что заняли. Выберите другое.",
  service_not_found: "Услуга недоступна.",
  studio_not_found: "Студия не найдена.",
  too_soon: "На это время записаться уже нельзя — слишком скоро.",
  too_far: "На такую дату запись пока не открыта.",
  in_the_past: "Это время уже прошло.",
  outside_working_hours: "Студия принимает автомобили в другое время.",
  time_not_aligned: "Выберите время из списка.",
  idempotency_key_reused: "Данные записи изменились. Подтвердите ещё раз.",
  cancel_window_closed: "Отменить онлайн уже нельзя — позвоните в студию.",
  cancel_not_allowed: "Эту запись нельзя отменить онлайн — позвоните в студию.",
  booking_not_found: "Запись не найдена.",
  booking_not_active: "Запись уже отменена или недоступна для изменения.",
  booking_token_required: "Нужна ссылка на запись.",
  invalid_credentials: "Неверная почта или пароль.",
  wrong_password: "Текущий пароль указан неверно.",
  not_authenticated: "Войдите в кабинет.",
  no_membership: "У вас нет доступа к этой студии.",
  bad_csrf: "Сессия устарела. Обновите страницу.",
  refund_exceeds_paid: "Возврат не может быть больше полученной оплаты.",
  invalid_amount: "Введите сумму больше нуля.",
  not_an_image: "Файл не похож на изображение.",
  unsupported_format: "Подходят только JPG, PNG и WebP.",
  file_too_large: "Файл слишком большой.",
  push_not_configured: "Уведомления на сервере пока не настроены.",
  no_push_subscription: "Сначала включите уведомления на этом устройстве.",
  push_failed: "Сервис уведомлений не принял сообщение. Выключите и снова включите уведомления.",
  resource_not_suitable: "Это место не подходит для услуги.",
  resource_limit: "У мастера одно рабочее место — добавить второго нельзя.",
  feature_disabled: "Эта возможность недоступна для вашего типа бизнеса.",
  car_required: "Укажите автомобиль.",
  resource_choice_not_allowed: "Выбор мастера здесь недоступен.",
  studio_suspended: "Онлайн-запись студии временно недоступна. Позвоните в студию.",
  plan_limit_bookings: "Достигнут лимит записей на тарифе. Свяжитесь со студией.",
  plan_limit_resources: "Достигнут лимит тарифа. Смените тариф, чтобы добавить больше.",
  close_before_open: "Время закрытия должно быть позже открытия.",
};

export function errorMessage(code: string, status = 0): string {
  return MESSAGES[code] ?? (status === 401 ? MESSAGES.not_authenticated : MESSAGES.server_error);
}
